project:
  type: website
  output-dir: docs

website:
  title: "Data Analytics Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
